// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: prime.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Prime {
  public static partial class PrimeNumberService
  {
    static readonly string __ServiceName = "prime.PrimeNumberService";

    static readonly grpc::Marshaller<global::Prime.PrimeNumberDecompositionRequest> __Marshaller_prime_PrimeNumberDecompositionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Prime.PrimeNumberDecompositionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Prime.PrimeNumberDecompositionResponse> __Marshaller_prime_PrimeNumberDecompositionResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Prime.PrimeNumberDecompositionResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Prime.PrimeNumberDecompositionRequest, global::Prime.PrimeNumberDecompositionResponse> __Method_PrimeNumberDecomposition = new grpc::Method<global::Prime.PrimeNumberDecompositionRequest, global::Prime.PrimeNumberDecompositionResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "PrimeNumberDecomposition",
        __Marshaller_prime_PrimeNumberDecompositionRequest,
        __Marshaller_prime_PrimeNumberDecompositionResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Prime.PrimeReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PrimeNumberService</summary>
    [grpc::BindServiceMethod(typeof(PrimeNumberService), "BindService")]
    public abstract partial class PrimeNumberServiceBase
    {
      public virtual global::System.Threading.Tasks.Task PrimeNumberDecomposition(global::Prime.PrimeNumberDecompositionRequest request, grpc::IServerStreamWriter<global::Prime.PrimeNumberDecompositionResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PrimeNumberService</summary>
    public partial class PrimeNumberServiceClient : grpc::ClientBase<PrimeNumberServiceClient>
    {
      /// <summary>Creates a new client for PrimeNumberService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PrimeNumberServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PrimeNumberService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PrimeNumberServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PrimeNumberServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PrimeNumberServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Prime.PrimeNumberDecompositionResponse> PrimeNumberDecomposition(global::Prime.PrimeNumberDecompositionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PrimeNumberDecomposition(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Prime.PrimeNumberDecompositionResponse> PrimeNumberDecomposition(global::Prime.PrimeNumberDecompositionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_PrimeNumberDecomposition, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PrimeNumberServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PrimeNumberServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PrimeNumberServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_PrimeNumberDecomposition, serviceImpl.PrimeNumberDecomposition).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PrimeNumberServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_PrimeNumberDecomposition, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Prime.PrimeNumberDecompositionRequest, global::Prime.PrimeNumberDecompositionResponse>(serviceImpl.PrimeNumberDecomposition));
    }

  }
}
#endregion
